import { HeaderLayout } from '@/components/layouts/header-layout'

export default function About() {
  return (
    <HeaderLayout>
      <div className="prose p-10 prose-headings:text-xl dark:prose-invert">
        <h1>About</h1>
        <p>101.school is an experiment in creating AI generated course contents.</p>

        <p>
          It works like this: you enter something you&apos;re curious about and then we
          generate a course on the subject. The course is generated by GPT-4 based on your
          input.
        </p>

        <p>
          You can choose to receive the course via email, or read it on the site.
          We&apos;ll keep track of your progress.
        </p>

        <p>
          You can also chat with the AI to ask it questions about any given unit in the
          course.
        </p>

        <p>
          An <a href="https://alexmaccaw.com">Alex MacCaw</a> project.
        </p>
      </div>
    </HeaderLayout>
  )
}
